#ifdef __CLING__
#pragma cling optimize(0)
#endif
void plot_fig_6_a()
{
   gROOT->SetBatch(kTRUE);
//=========Macro generated from canvas: goodPhotonSR_et/goodPhotonSR_et
//=========  (Sun Mar 31 12:51:37 2024) by ROOT version 6.26/08
   TCanvas *goodPhotonSR_et = new TCanvas("goodPhotonSR_et", "goodPhotonSR_et",0,0,800,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   goodPhotonSR_et->SetHighLightColor(2);
   goodPhotonSR_et->Range(0,0,1,1);
   goodPhotonSR_et->SetFillColor(0);
   goodPhotonSR_et->SetBorderMode(0);
   goodPhotonSR_et->SetBorderSize(2);
   goodPhotonSR_et->SetTickx(1);
   goodPhotonSR_et->SetTicky(1);
   goodPhotonSR_et->SetLeftMargin(0.16);
   goodPhotonSR_et->SetRightMargin(0.15);
   goodPhotonSR_et->SetTopMargin(0.06);
   goodPhotonSR_et->SetBottomMargin(0.3);
   goodPhotonSR_et->SetFrameFillStyle(0);
   goodPhotonSR_et->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: goodPhotonSR_et_1
   TPad *goodPhotonSR_et_1 = new TPad("goodPhotonSR_et_1", "goodPhotonSR_et_1",0,0.3,1,1);
   goodPhotonSR_et_1->Draw();
   goodPhotonSR_et_1->cd();
   goodPhotonSR_et_1->Range(0.6086958,0,9.304348,38.46154);
   goodPhotonSR_et_1->SetFillColor(0);
   goodPhotonSR_et_1->SetBorderMode(0);
   goodPhotonSR_et_1->SetBorderSize(2);
   goodPhotonSR_et_1->SetLeftMargin(0.16);
   goodPhotonSR_et_1->SetRightMargin(0.15);
   goodPhotonSR_et_1->SetBottomMargin(0);
   goodPhotonSR_et_1->SetFrameFillStyle(0);
   goodPhotonSR_et_1->SetFrameBorderMode(0);
   goodPhotonSR_et_1->SetFrameFillStyle(0);
   goodPhotonSR_et_1->SetFrameLineWidth(2);
   goodPhotonSR_et_1->SetFrameBorderMode(0);
   goodPhotonSR_et_1->SetFrameBorderSize(2);
   
   THStack *goodPhotonSR_etbackground = new THStack();
   goodPhotonSR_etbackground->SetName("goodPhotonSR_etbackground");
   goodPhotonSR_etbackground->SetTitle("");
   goodPhotonSR_etbackground->SetMaximum(35);
   
   TH1F *goodPhotonSR_etbackground_stack_1 = new TH1F("goodPhotonSR_etbackground_stack_1","",5,2,8);
   goodPhotonSR_etbackground_stack_1->SetMinimum(0);
   goodPhotonSR_etbackground_stack_1->SetMaximum(35);
   goodPhotonSR_etbackground_stack_1->SetDirectory(0);
   goodPhotonSR_etbackground_stack_1->SetStats(0);
   goodPhotonSR_etbackground_stack_1->SetLineStyle(0);
   goodPhotonSR_etbackground_stack_1->GetXaxis()->SetTitle("E_{T}^{#gamma} (GeV)");
   goodPhotonSR_etbackground_stack_1->GetXaxis()->SetLabelFont(42);
   goodPhotonSR_etbackground_stack_1->GetXaxis()->SetLabelOffset(0.007);
   goodPhotonSR_etbackground_stack_1->GetXaxis()->SetLabelSize(0.06);
   goodPhotonSR_etbackground_stack_1->GetXaxis()->SetTitleSize(0.06);
   goodPhotonSR_etbackground_stack_1->GetXaxis()->SetTitleOffset(1.7);
   goodPhotonSR_etbackground_stack_1->GetXaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground_stack_1->GetYaxis()->SetTitle("Events / 1.2 GeV");
   goodPhotonSR_etbackground_stack_1->GetYaxis()->CenterTitle(true);
   goodPhotonSR_etbackground_stack_1->GetYaxis()->SetNdivisions(505);
   goodPhotonSR_etbackground_stack_1->GetYaxis()->SetLabelFont(42);
   goodPhotonSR_etbackground_stack_1->GetYaxis()->SetLabelOffset(0.007);
   goodPhotonSR_etbackground_stack_1->GetYaxis()->SetLabelSize(0.06);
   goodPhotonSR_etbackground_stack_1->GetYaxis()->SetTitleSize(0.05);
   goodPhotonSR_etbackground_stack_1->GetYaxis()->SetTitleOffset(1.5);
   goodPhotonSR_etbackground_stack_1->GetYaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground_stack_1->GetZaxis()->SetLabelFont(42);
   goodPhotonSR_etbackground_stack_1->GetZaxis()->SetLabelOffset(0.007);
   goodPhotonSR_etbackground_stack_1->GetZaxis()->SetLabelSize(0.05);
   goodPhotonSR_etbackground_stack_1->GetZaxis()->SetTitleSize(0.06);
   goodPhotonSR_etbackground_stack_1->GetZaxis()->SetTitleOffset(1);
   goodPhotonSR_etbackground_stack_1->GetZaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground->SetHistogram(goodPhotonSR_etbackground_stack_1);
   
   
   TH1D *goodPhotonSR_et_stack_1 = new TH1D("goodPhotonSR_et_stack_1","goodPhotonSR_et",5,2,8);
   goodPhotonSR_et_stack_1->SetBinContent(1,7.885605);
   goodPhotonSR_et_stack_1->SetBinContent(2,7.472914);
   goodPhotonSR_et_stack_1->SetBinContent(3,2.710908);
   goodPhotonSR_et_stack_1->SetBinContent(4,1.097214);
   goodPhotonSR_et_stack_1->SetBinContent(5,0.5436644);
   goodPhotonSR_et_stack_1->SetBinContent(6,0.4991827);
   goodPhotonSR_et_stack_1->SetBinError(1,0.1395956);
   goodPhotonSR_et_stack_1->SetBinError(2,0.1358936);
   goodPhotonSR_et_stack_1->SetBinError(3,0.08184865);
   goodPhotonSR_et_stack_1->SetBinError(4,0.05207145);
   goodPhotonSR_et_stack_1->SetBinError(5,0.03665384);
   goodPhotonSR_et_stack_1->SetBinError(6,0.03512238);
   goodPhotonSR_et_stack_1->SetEntries(8178);
   goodPhotonSR_et_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#6699ff");
   goodPhotonSR_et_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   goodPhotonSR_et_stack_1->SetLineColor(ci);
   goodPhotonSR_et_stack_1->SetMarkerStyle(20);
   goodPhotonSR_et_stack_1->GetXaxis()->SetRange(1,5);
   goodPhotonSR_et_stack_1->GetXaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_1->GetXaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_1->GetXaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_1->GetYaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_1->GetYaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_1->GetZaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_1->GetZaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_1->GetZaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground->Add(goodPhotonSR_et_stack_1,"");
   
   TH1D *goodPhotonSR_et_stack_2 = new TH1D("goodPhotonSR_et_stack_2","goodPhotonSR_et",5,2,8);
   goodPhotonSR_et_stack_2->SetBinContent(1,0.5749687);
   goodPhotonSR_et_stack_2->SetBinContent(2,0.5174719);
   goodPhotonSR_et_stack_2->SetBinContent(3,0.3449812);
   goodPhotonSR_et_stack_2->SetBinContent(4,0.05749687);
   goodPhotonSR_et_stack_2->SetBinError(1,0.1818211);
   goodPhotonSR_et_stack_2->SetBinError(2,0.1724906);
   goodPhotonSR_et_stack_2->SetBinError(3,0.140838);
   goodPhotonSR_et_stack_2->SetBinError(4,0.05749687);
   goodPhotonSR_et_stack_2->SetEntries(26);
   goodPhotonSR_et_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#ffff00");
   goodPhotonSR_et_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   goodPhotonSR_et_stack_2->SetLineColor(ci);
   goodPhotonSR_et_stack_2->SetMarkerStyle(20);
   goodPhotonSR_et_stack_2->SetMarkerSize(0);
   goodPhotonSR_et_stack_2->GetXaxis()->SetRange(1,5);
   goodPhotonSR_et_stack_2->GetXaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_2->GetXaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_2->GetXaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_2->GetYaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_2->GetYaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_2->GetZaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_2->GetZaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_2->GetZaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground->Add(goodPhotonSR_et_stack_2,"");
   
   TH1D *goodPhotonSR_et_stack_3 = new TH1D("goodPhotonSR_et_stack_3","goodPhotonSR_et",5,2,8);
   goodPhotonSR_et_stack_3->SetBinContent(1,0.7218262);
   goodPhotonSR_et_stack_3->SetBinContent(2,0.8661914);
   goodPhotonSR_et_stack_3->SetBinContent(3,0.2887305);
   goodPhotonSR_et_stack_3->SetBinContent(4,0.2165479);
   goodPhotonSR_et_stack_3->SetBinContent(5,0.07218262);
   goodPhotonSR_et_stack_3->SetBinContent(6,0.1443652);
   goodPhotonSR_et_stack_3->SetBinError(1,0.2282615);
   goodPhotonSR_et_stack_3->SetBinError(2,0.2500479);
   goodPhotonSR_et_stack_3->SetBinError(3,0.1443652);
   goodPhotonSR_et_stack_3->SetBinError(4,0.125024);
   goodPhotonSR_et_stack_3->SetBinError(5,0.07218262);
   goodPhotonSR_et_stack_3->SetBinError(6,0.1020816);
   goodPhotonSR_et_stack_3->SetEntries(32);
   goodPhotonSR_et_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#ffff00");
   goodPhotonSR_et_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   goodPhotonSR_et_stack_3->SetLineColor(ci);
   goodPhotonSR_et_stack_3->SetMarkerStyle(20);
   goodPhotonSR_et_stack_3->SetMarkerSize(0);
   goodPhotonSR_et_stack_3->GetXaxis()->SetRange(1,5);
   goodPhotonSR_et_stack_3->GetXaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_3->GetXaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_3->GetXaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_3->GetYaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_3->GetYaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_3->GetZaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_3->GetZaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_3->GetZaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground->Add(goodPhotonSR_et_stack_3,"");
   
   TH1D *goodPhotonSR_et_stack_4 = new TH1D("goodPhotonSR_et_stack_4","goodPhotonSR_et",5,2,8);
   goodPhotonSR_et_stack_4->SetBinContent(1,8.370766);
   goodPhotonSR_et_stack_4->SetBinContent(2,8.845863);
   goodPhotonSR_et_stack_4->SetBinContent(3,4.304157);
   goodPhotonSR_et_stack_4->SetBinContent(4,1.538411);
   goodPhotonSR_et_stack_4->SetBinContent(5,0.9106036);
   goodPhotonSR_et_stack_4->SetBinContent(6,1.674153);
   goodPhotonSR_et_stack_4->SetBinError(1,0.2175877);
   goodPhotonSR_et_stack_4->SetBinError(2,0.2236773);
   goodPhotonSR_et_stack_4->SetBinError(3,0.1560256);
   goodPhotonSR_et_stack_4->SetBinError(4,0.09327987);
   goodPhotonSR_et_stack_4->SetBinError(5,0.07176561);
   goodPhotonSR_et_stack_4->SetBinError(6,0.09730817);
   goodPhotonSR_et_stack_4->SetEntries(4534);
   goodPhotonSR_et_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   goodPhotonSR_et_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   goodPhotonSR_et_stack_4->SetLineColor(ci);
   goodPhotonSR_et_stack_4->SetMarkerStyle(20);
   goodPhotonSR_et_stack_4->GetXaxis()->SetRange(1,5);
   goodPhotonSR_et_stack_4->GetXaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_4->GetXaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_4->GetXaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_4->GetYaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_4->GetYaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_4->GetZaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_4->GetZaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_4->GetZaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground->Add(goodPhotonSR_et_stack_4,"");
   goodPhotonSR_etbackground->Draw("hist");
   
   auto goodPhotonSR_etdata = new THStack();
   goodPhotonSR_etdata->SetName("goodPhotonSR_etdata");
   goodPhotonSR_etdata->SetTitle("");
   goodPhotonSR_etdata->SetMaximum(35);
   
   TH1F *goodPhotonSR_etdata_stack_2 = new TH1F("goodPhotonSR_etdata_stack_2","",5,2,8);
   goodPhotonSR_etdata_stack_2->SetMinimum(0);
   goodPhotonSR_etdata_stack_2->SetMaximum(35);
   goodPhotonSR_etdata_stack_2->SetDirectory(0);
   goodPhotonSR_etdata_stack_2->SetStats(0);
   goodPhotonSR_etdata_stack_2->SetLineStyle(0);
   goodPhotonSR_etdata_stack_2->GetXaxis()->SetTitle("E_{T}^{#gamma} (GeV)");
   goodPhotonSR_etdata_stack_2->GetXaxis()->SetLabelFont(42);
   goodPhotonSR_etdata_stack_2->GetXaxis()->SetLabelOffset(0.007);
   goodPhotonSR_etdata_stack_2->GetXaxis()->SetLabelSize(0.06);
   goodPhotonSR_etdata_stack_2->GetXaxis()->SetTitleSize(0.06);
   goodPhotonSR_etdata_stack_2->GetXaxis()->SetTitleOffset(1.7);
   goodPhotonSR_etdata_stack_2->GetXaxis()->SetTitleFont(42);
   goodPhotonSR_etdata_stack_2->GetYaxis()->SetTitle("Events / 1.2 GeV");
   goodPhotonSR_etdata_stack_2->GetYaxis()->CenterTitle(true);
   goodPhotonSR_etdata_stack_2->GetYaxis()->SetNdivisions(505);
   goodPhotonSR_etdata_stack_2->GetYaxis()->SetLabelFont(42);
   goodPhotonSR_etdata_stack_2->GetYaxis()->SetLabelOffset(0.007);
   goodPhotonSR_etdata_stack_2->GetYaxis()->SetLabelSize(0.06);
   goodPhotonSR_etdata_stack_2->GetYaxis()->SetTitleSize(0.05);
   goodPhotonSR_etdata_stack_2->GetYaxis()->SetTitleOffset(1.5);
   goodPhotonSR_etdata_stack_2->GetYaxis()->SetTitleFont(42);
   goodPhotonSR_etdata_stack_2->GetZaxis()->SetLabelFont(42);
   goodPhotonSR_etdata_stack_2->GetZaxis()->SetLabelOffset(0.007);
   goodPhotonSR_etdata_stack_2->GetZaxis()->SetLabelSize(0.05);
   goodPhotonSR_etdata_stack_2->GetZaxis()->SetTitleSize(0.06);
   goodPhotonSR_etdata_stack_2->GetZaxis()->SetTitleOffset(1);
   goodPhotonSR_etdata_stack_2->GetZaxis()->SetTitleFont(42);
   goodPhotonSR_etdata->SetHistogram(goodPhotonSR_etdata_stack_2);
   
   
   goodPhotonSR_et_stack_1 = new TH1D("goodPhotonSR_et_stack_1","goodPhotonSR_et",5,2,8);
   goodPhotonSR_et_stack_1->SetBinContent(1,15);
   goodPhotonSR_et_stack_1->SetBinContent(2,24);
   goodPhotonSR_et_stack_1->SetBinContent(3,6);
   goodPhotonSR_et_stack_1->SetBinContent(4,7);
   goodPhotonSR_et_stack_1->SetBinError(1,3.872983);
   goodPhotonSR_et_stack_1->SetBinError(2,4.898979);
   goodPhotonSR_et_stack_1->SetBinError(3,2.44949);
   goodPhotonSR_et_stack_1->SetBinError(4,2.645751);
   goodPhotonSR_et_stack_1->SetEntries(52);
   goodPhotonSR_et_stack_1->SetDirectory(0);

   ci = 1482;
   color = new TColor(ci, 0, 1, 0, " ", 0);
   goodPhotonSR_et_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   goodPhotonSR_et_stack_1->SetLineColor(ci);
   goodPhotonSR_et_stack_1->SetMarkerStyle(20);
   goodPhotonSR_et_stack_1->GetXaxis()->SetRange(1,5);
   goodPhotonSR_et_stack_1->GetXaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_1->GetXaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_1->GetXaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_1->GetYaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_1->GetYaxis()->SetTitleFont(42);
   goodPhotonSR_et_stack_1->GetZaxis()->SetLabelFont(42);
   goodPhotonSR_et_stack_1->GetZaxis()->SetTitleOffset(1);
   goodPhotonSR_et_stack_1->GetZaxis()->SetTitleFont(42);
   goodPhotonSR_etdata->Add(goodPhotonSR_et_stack_1,"");
   goodPhotonSR_etdata->Draw("nostack pe0 same");
   
   TH1D *backgrounds_unc_goodPhotonSR_et__1 = new TH1D("backgrounds_unc_goodPhotonSR_et__1","goodPhotonSR_et",5,2,8);
   backgrounds_unc_goodPhotonSR_et__1->SetBinContent(1,17.55317);
   backgrounds_unc_goodPhotonSR_et__1->SetBinContent(2,17.70244);
   backgrounds_unc_goodPhotonSR_et__1->SetBinContent(3,7.648777);
   backgrounds_unc_goodPhotonSR_et__1->SetBinContent(4,2.909669);
   backgrounds_unc_goodPhotonSR_et__1->SetBinContent(5,1.526451);
   backgrounds_unc_goodPhotonSR_et__1->SetBinContent(6,2.317701);
   backgrounds_unc_goodPhotonSR_et__1->SetBinError(1,4.056008);
   backgrounds_unc_goodPhotonSR_et__1->SetBinError(2,4.091257);
   backgrounds_unc_goodPhotonSR_et__1->SetBinError(3,1.779486);
   backgrounds_unc_goodPhotonSR_et__1->SetBinError(4,0.6915274);
   backgrounds_unc_goodPhotonSR_et__1->SetBinError(5,0.3673743);
   backgrounds_unc_goodPhotonSR_et__1->SetBinError(6,0.145338);
   backgrounds_unc_goodPhotonSR_et__1->SetEntries(12770);

   ci = 1555;
   color = new TColor(ci, 0, 0, 0, " ", 0.3);
   backgrounds_unc_goodPhotonSR_et__1->SetFillColor(ci);
   backgrounds_unc_goodPhotonSR_et__1->SetFillStyle(3244);
   backgrounds_unc_goodPhotonSR_et__1->SetMarkerStyle(20);
   backgrounds_unc_goodPhotonSR_et__1->SetMarkerSize(0);
   backgrounds_unc_goodPhotonSR_et__1->GetXaxis()->SetRange(1,5);
   backgrounds_unc_goodPhotonSR_et__1->GetXaxis()->SetLabelFont(42);
   backgrounds_unc_goodPhotonSR_et__1->GetXaxis()->SetTitleOffset(1);
   backgrounds_unc_goodPhotonSR_et__1->GetXaxis()->SetTitleFont(42);
   backgrounds_unc_goodPhotonSR_et__1->GetYaxis()->SetLabelFont(42);
   backgrounds_unc_goodPhotonSR_et__1->GetYaxis()->SetTitleFont(42);
   backgrounds_unc_goodPhotonSR_et__1->GetZaxis()->SetLabelFont(42);
   backgrounds_unc_goodPhotonSR_et__1->GetZaxis()->SetTitleOffset(1);
   backgrounds_unc_goodPhotonSR_et__1->GetZaxis()->SetTitleFont(42);
   backgrounds_unc_goodPhotonSR_et__1->Draw("same e2");
   
   TLegend *leg = new TLegend(0.62,0.7,0.82,0.75,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("goodPhotonSR_et_stack_3","#gamma#gamma#rightarrowe^{+}e^{-}","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.72,0.75,0.82,0.8,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   leg->Draw();
   
   leg = new TLegend(0.62,0.8,0.82,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("goodPhotonSR_et_stack_1","Data","pl");

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.62,0.75,0.82,0.8,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("goodPhotonSR_et_stack_4","#gamma#gamma#rightarrow#gamma#gamma","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.62,0.65,0.82,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("goodPhotonSR_et_stack_1","gg#rightarrow#gamma#gamma","f");

   ci = TColor::GetColor("#6699ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1F *goodPhotonSR_etbackground_copy__2 = new TH1F("goodPhotonSR_etbackground_copy__2","",5,2,8);
   goodPhotonSR_etbackground_copy__2->SetMinimum(0);
   goodPhotonSR_etbackground_copy__2->SetMaximum(35);
   goodPhotonSR_etbackground_copy__2->SetDirectory(0);
   goodPhotonSR_etbackground_copy__2->SetStats(0);
   goodPhotonSR_etbackground_copy__2->SetLineStyle(0);
   goodPhotonSR_etbackground_copy__2->GetXaxis()->SetTitle("E_{T}^{#gamma} (GeV)");
   goodPhotonSR_etbackground_copy__2->GetXaxis()->SetLabelFont(42);
   goodPhotonSR_etbackground_copy__2->GetXaxis()->SetLabelOffset(0.007);
   goodPhotonSR_etbackground_copy__2->GetXaxis()->SetLabelSize(0.06);
   goodPhotonSR_etbackground_copy__2->GetXaxis()->SetTitleSize(0.06);
   goodPhotonSR_etbackground_copy__2->GetXaxis()->SetTitleOffset(1.7);
   goodPhotonSR_etbackground_copy__2->GetXaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground_copy__2->GetYaxis()->SetTitle("Events / 1.2 GeV");
   goodPhotonSR_etbackground_copy__2->GetYaxis()->CenterTitle(true);
   goodPhotonSR_etbackground_copy__2->GetYaxis()->SetNdivisions(505);
   goodPhotonSR_etbackground_copy__2->GetYaxis()->SetLabelFont(42);
   goodPhotonSR_etbackground_copy__2->GetYaxis()->SetLabelOffset(0.007);
   goodPhotonSR_etbackground_copy__2->GetYaxis()->SetLabelSize(0.06);
   goodPhotonSR_etbackground_copy__2->GetYaxis()->SetTitleSize(0.05);
   goodPhotonSR_etbackground_copy__2->GetYaxis()->SetTitleOffset(1.5);
   goodPhotonSR_etbackground_copy__2->GetYaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground_copy__2->GetZaxis()->SetLabelFont(42);
   goodPhotonSR_etbackground_copy__2->GetZaxis()->SetLabelOffset(0.007);
   goodPhotonSR_etbackground_copy__2->GetZaxis()->SetLabelSize(0.05);
   goodPhotonSR_etbackground_copy__2->GetZaxis()->SetTitleSize(0.06);
   goodPhotonSR_etbackground_copy__2->GetZaxis()->SetTitleOffset(1);
   goodPhotonSR_etbackground_copy__2->GetZaxis()->SetTitleFont(42);
   goodPhotonSR_etbackground_copy__2->Draw("sameaxis");
   goodPhotonSR_et_1->Modified();
   goodPhotonSR_et->cd();
  
// ------------>Primitives in pad: goodPhotonSR_et_2
   TPad *goodPhotonSR_et_2 = new TPad("goodPhotonSR_et_2", "goodPhotonSR_et_2",0,0,1,0.3);
   goodPhotonSR_et_2->Draw();
   goodPhotonSR_et_2->cd();
   goodPhotonSR_et_2->Range(0.6086958,-0.8571429,9.304348,2);
   goodPhotonSR_et_2->SetFillColor(0);
   goodPhotonSR_et_2->SetBorderMode(0);
   goodPhotonSR_et_2->SetBorderSize(2);
   goodPhotonSR_et_2->SetLeftMargin(0.16);
   goodPhotonSR_et_2->SetRightMargin(0.15);
   goodPhotonSR_et_2->SetTopMargin(0);
   goodPhotonSR_et_2->SetBottomMargin(0.3);
   goodPhotonSR_et_2->SetFrameFillStyle(0);
   goodPhotonSR_et_2->SetFrameBorderMode(0);
   goodPhotonSR_et_2->SetFrameFillStyle(0);
   goodPhotonSR_et_2->SetFrameBorderMode(0);
   
   auto ratio_stack_goodPhotonSR_et = new THStack();
   ratio_stack_goodPhotonSR_et->SetName("ratio_stack_goodPhotonSR_et");
   ratio_stack_goodPhotonSR_et->SetTitle("");
   ratio_stack_goodPhotonSR_et->SetMinimum(0);
   ratio_stack_goodPhotonSR_et->SetMaximum(2);
   
   TH1F *ratio_stack_goodPhotonSR_et_stack_3 = new TH1F("ratio_stack_goodPhotonSR_et_stack_3","",5,2,8);
   ratio_stack_goodPhotonSR_et_stack_3->SetMinimum(0);
   ratio_stack_goodPhotonSR_et_stack_3->SetMaximum(2);
   ratio_stack_goodPhotonSR_et_stack_3->SetDirectory(0);
   ratio_stack_goodPhotonSR_et_stack_3->SetStats(0);
   ratio_stack_goodPhotonSR_et_stack_3->SetLineStyle(0);
   ratio_stack_goodPhotonSR_et_stack_3->GetXaxis()->SetTitle("E_{T}^{#gamma} (GeV)");
   ratio_stack_goodPhotonSR_et_stack_3->GetXaxis()->SetLabelFont(42);
   ratio_stack_goodPhotonSR_et_stack_3->GetXaxis()->SetLabelOffset(0.007);
   ratio_stack_goodPhotonSR_et_stack_3->GetXaxis()->SetLabelSize(0.1);
   ratio_stack_goodPhotonSR_et_stack_3->GetXaxis()->SetTitleSize(0.12);
   ratio_stack_goodPhotonSR_et_stack_3->GetXaxis()->SetTitleOffset(1);
   ratio_stack_goodPhotonSR_et_stack_3->GetXaxis()->SetTitleFont(42);
   ratio_stack_goodPhotonSR_et_stack_3->GetYaxis()->SetTitle("Data/MC");
   ratio_stack_goodPhotonSR_et_stack_3->GetYaxis()->CenterTitle(true);
   ratio_stack_goodPhotonSR_et_stack_3->GetYaxis()->SetNdivisions(505);
   ratio_stack_goodPhotonSR_et_stack_3->GetYaxis()->SetLabelFont(42);
   ratio_stack_goodPhotonSR_et_stack_3->GetYaxis()->SetLabelOffset(0.007);
   ratio_stack_goodPhotonSR_et_stack_3->GetYaxis()->SetLabelSize(0.1);
   ratio_stack_goodPhotonSR_et_stack_3->GetYaxis()->SetTitleSize(0.1);
   ratio_stack_goodPhotonSR_et_stack_3->GetYaxis()->SetTitleOffset(0.5);
   ratio_stack_goodPhotonSR_et_stack_3->GetYaxis()->SetTitleFont(42);
   ratio_stack_goodPhotonSR_et_stack_3->GetZaxis()->SetLabelFont(42);
   ratio_stack_goodPhotonSR_et_stack_3->GetZaxis()->SetLabelOffset(0.007);
   ratio_stack_goodPhotonSR_et_stack_3->GetZaxis()->SetLabelSize(0.05);
   ratio_stack_goodPhotonSR_et_stack_3->GetZaxis()->SetTitleSize(0.06);
   ratio_stack_goodPhotonSR_et_stack_3->GetZaxis()->SetTitleOffset(1);
   ratio_stack_goodPhotonSR_et_stack_3->GetZaxis()->SetTitleFont(42);
   ratio_stack_goodPhotonSR_et->SetHistogram(ratio_stack_goodPhotonSR_et_stack_3);
   
   
   TH1D *ratio_goodPhotonSR_et_stack_1 = new TH1D("ratio_goodPhotonSR_et_stack_1","goodPhotonSR_et",5,2,8);
   ratio_goodPhotonSR_et_stack_1->SetBinContent(1,0.8545467);
   ratio_goodPhotonSR_et_stack_1->SetBinContent(2,1.355745);
   ratio_goodPhotonSR_et_stack_1->SetBinContent(3,0.7844391);
   ratio_goodPhotonSR_et_stack_1->SetBinContent(4,2.405772);
   ratio_goodPhotonSR_et_stack_1->SetBinError(1,0.2214578);
   ratio_goodPhotonSR_et_stack_1->SetBinError(2,0.2784389);
   ratio_goodPhotonSR_et_stack_1->SetBinError(3,0.3214215);
   ratio_goodPhotonSR_et_stack_1->SetBinError(4,0.9206343);
   ratio_goodPhotonSR_et_stack_1->SetEntries(27.06891);

   ci = 1482;
   color = new TColor(ci, 0, 1, 0, " ", 0);
   ratio_goodPhotonSR_et_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#000000");
   ratio_goodPhotonSR_et_stack_1->SetLineColor(ci);
   ratio_goodPhotonSR_et_stack_1->SetMarkerStyle(20);
   ratio_goodPhotonSR_et_stack_1->GetXaxis()->SetRange(1,5);
   ratio_goodPhotonSR_et_stack_1->GetXaxis()->SetLabelFont(42);
   ratio_goodPhotonSR_et_stack_1->GetXaxis()->SetTitleOffset(1);
   ratio_goodPhotonSR_et_stack_1->GetXaxis()->SetTitleFont(42);
   ratio_goodPhotonSR_et_stack_1->GetYaxis()->SetLabelFont(42);
   ratio_goodPhotonSR_et_stack_1->GetYaxis()->SetTitleFont(42);
   ratio_goodPhotonSR_et_stack_1->GetZaxis()->SetLabelFont(42);
   ratio_goodPhotonSR_et_stack_1->GetZaxis()->SetTitleOffset(1);
   ratio_goodPhotonSR_et_stack_1->GetZaxis()->SetTitleFont(42);
   ratio_stack_goodPhotonSR_et->Add(ratio_goodPhotonSR_et_stack_1,"");
   ratio_stack_goodPhotonSR_et->Draw("p");
   TLine *line = new TLine(2,1,8,1);
   line->SetLineStyle(2);
   line->Draw();
   
   TH1D *ratio_uncertainty_goodPhotonSR_et__3 = new TH1D("ratio_uncertainty_goodPhotonSR_et__3","goodPhotonSR_et",5,2,8);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinContent(1,1);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinContent(2,1);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinContent(3,1);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinContent(4,1);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinContent(5,1);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinContent(6,1);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinError(1,0.3267822);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinError(2,0.3268426);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinError(3,0.3290164);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinError(4,0.3361095);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinError(5,0.3403619);
   ratio_uncertainty_goodPhotonSR_et__3->SetBinError(6,0.08868224);
   ratio_uncertainty_goodPhotonSR_et__3->SetEntries(45.39839);

   ci = 1555;
   color = new TColor(ci, 0, 0, 0, " ", 0.3);
   ratio_uncertainty_goodPhotonSR_et__3->SetFillColor(ci);
   ratio_uncertainty_goodPhotonSR_et__3->SetFillStyle(3244);
   ratio_uncertainty_goodPhotonSR_et__3->SetMarkerStyle(20);
   ratio_uncertainty_goodPhotonSR_et__3->SetMarkerSize(0);
   ratio_uncertainty_goodPhotonSR_et__3->GetXaxis()->SetRange(1,5);
   ratio_uncertainty_goodPhotonSR_et__3->GetXaxis()->SetLabelFont(42);
   ratio_uncertainty_goodPhotonSR_et__3->GetXaxis()->SetTitleOffset(1);
   ratio_uncertainty_goodPhotonSR_et__3->GetXaxis()->SetTitleFont(42);
   ratio_uncertainty_goodPhotonSR_et__3->GetYaxis()->SetLabelFont(42);
   ratio_uncertainty_goodPhotonSR_et__3->GetYaxis()->SetTitleFont(42);
   ratio_uncertainty_goodPhotonSR_et__3->GetZaxis()->SetLabelFont(42);
   ratio_uncertainty_goodPhotonSR_et__3->GetZaxis()->SetTitleOffset(1);
   ratio_uncertainty_goodPhotonSR_et__3->GetZaxis()->SetTitleFont(42);
   ratio_uncertainty_goodPhotonSR_et__3->Draw("same e2");
   goodPhotonSR_et_2->Modified();
   goodPhotonSR_et->cd();
   TLatex *   tex = new TLatex(0.85,0.928,"1.6 nb^{-1} ( PbPb @ 5.02 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.036);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19105,0.9176,"CMS");
   tex->SetTextAlign(13);
   tex->SetTextFont(61);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19105,0.8636,"Preliminary");
   tex->SetTextAlign(13);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0342);
   tex->SetLineWidth(2);
   tex->Draw();
   goodPhotonSR_et->Modified();
   goodPhotonSR_et->cd();
   goodPhotonSR_et->SetSelected(goodPhotonSR_et);
   goodPhotonSR_et->SaveAs("Figure_006_a.pdf");
}
